let currentLanguage=localStorage.getItem('h1apps-language')||'en';
const firebaseConfig={apiKey:'AIzaSyDOlDg14fbH8kXfSbr6YCj6NECtEPJIdiU',authDomain:'h1words.firebaseapp.com',projectId:'h1words',storageBucket:'h1words.firebasestorage.app',messagingSenderId:'594662600507',appId:'1:594662600507:web:h1appswebsite'};
const labels={ar:{navAbout:'من نحن',navProducts:'منتجاتنا',navContact:'تواصل معنا',aboutKicker:'من نحن',missionKicker:'رسالتنا',visionKicker:'رؤيتنا',valuesKicker:'ما يؤمن به فريقنا',storyKicker:'قصتنا',startKicker:'هل نبدأ؟',direction:'rtl'},en:{navAbout:'About us',navProducts:'Our work',navContact:'Contact',aboutKicker:'About us',missionKicker:'Our mission',visionKicker:'Our vision',valuesKicker:'What we believe in',storyKicker:'Our story',startKicker:'Shall we start?',direction:'ltr'}};
const fields=['brandName','brandTagline','aboutTitle','aboutIntro','missionTitle','missionText','visionTitle','visionText','valuesTitle','valuesDescription','valueOneTitle','valueOneText','valueTwoTitle','valueTwoText','valueThreeTitle','valueThreeText','storyTitle','storyText','statOneValue','statOneLabel','statTwoValue','statTwoLabel','statThreeValue','statThreeLabel','ctaTitle','ctaText','ctaButtonText','ctaButtonUrl','footerText'];
const safeHref=(value)=>{try{const url=new URL(String(value||''),window.location.href);return ['http:','https:','mailto:','tel:'].includes(url.protocol)?url.href:''}catch(_){return ''}};
const read=(data,key)=>currentLanguage==='en'?data[`${key}En`]:data[key];
function clearPage(){document.body.classList.remove('data-pending');fields.forEach(key=>{const el=document.getElementById(key);if(el){el.textContent='';if(key==='ctaButtonUrl')el.removeAttribute('href')}});document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent='');document.querySelector('main')?.classList.add('site-data-empty')}
function render(data){if(!data||!Object.keys(data).length){clearPage();return}document.body.classList.remove('data-pending');document.querySelector('main')?.classList.remove('site-data-empty');fields.forEach(key=>{const el=document.getElementById(key);if(el)el.textContent=read(data,key)||''});const button=document.getElementById('ctaButton');if(button){button.textContent=`${read(data,'ctaButtonText')||''} ↗`;button.href=safeHref(data.ctaButtonUrl)}document.title=read(data,'aboutTitle')||'';document.querySelector('meta[name="description"]')?.setAttribute('content',read(data,'aboutIntro')||'');document.querySelector('meta[property="og:title"]')?.setAttribute('content',document.title);document.querySelector('meta[property="og:description"]')?.setAttribute('content',read(data,'aboutIntro')||'')}
function setLanguage(language){currentLanguage=language;localStorage.setItem('h1apps-language',language);document.documentElement.lang=language;document.documentElement.dir=labels[language].direction;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=labels[language][el.dataset.i18n]||'');document.getElementById('arButton')?.classList.toggle('active',language==='ar');document.getElementById('enButton')?.classList.toggle('active',language==='en');if(window.liveAboutData)render(window.liveAboutData)}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('arButton')?.addEventListener('click',()=>{localStorage.setItem('h1apps-language','ar');location.reload()});document.getElementById('enButton')?.addEventListener('click',()=>{localStorage.setItem('h1apps-language','en');location.reload()});setLanguage(currentLanguage)});
try{firebase.initializeApp(firebaseConfig);firebase.firestore().doc('site_about/about').get().then(snapshot=>{window.liveAboutData=snapshot.exists?snapshot.data():null;render(window.liveAboutData)}).catch(()=>clearPage())}catch(error){clearPage()}
