let language=localStorage.getItem('h1apps-language')||'en';
const contactForm=document.getElementById('contactForm'); if(contactForm){const trap=document.createElement('input');trap.className='form-trap';trap.name='website';trap.tabIndex=-1;trap.autocomplete='off';trap.setAttribute('aria-hidden','true');contactForm.prepend(trap)}
const firebaseConfig={apiKey:'AIzaSyDOlDg14fbH8kXfSbr6YCj6NECtEPJIdiU',authDomain:'h1words.firebaseapp.com',projectId:'h1words',storageBucket:'h1words.firebasestorage.app',messagingSenderId:'594662600507',appId:'1:594662600507:web:2fcbf66623066c7bc8d11e'};
const fields=['contactKicker','contactTitle','contactDescription','formKicker','formTitle','formDescription','emailLabel','whatsappLabel','addressLabel','nameLabel','emailFieldLabel','phoneLabel','companyLabel','messageLabel','consentLabel','submitText','footerText','footerDeletion'];
const text=(data,key)=>language==='en'?data[`${key}En`]:data[key];
const safeHref=(value)=>{try{const url=new URL(String(value||''),window.location.href);return ['http:','https:','mailto:','tel:'].includes(url.protocol)?url.href:''}catch(_){return ''}};
function clearPage(){document.body.classList.remove('data-pending');fields.forEach(key=>{const el=document.getElementById(key);if(el)el.textContent=''});['email','phoneText','addressText'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=''});document.getElementById('contactEmail')?.setAttribute('href','');document.getElementById('contactWhatsapp')?.setAttribute('href','');document.querySelector('.contact-shell')?.classList.add('site-data-empty')}
function render(data){if(!data||!Object.keys(data).length){clearPage();return}document.body.classList.remove('data-pending');document.querySelector('.contact-shell')?.classList.remove('site-data-empty');fields.forEach(key=>{const el=document.getElementById(key);if(el)el.textContent=text(data,key)||''});const email=data.email||'';document.getElementById('contactEmail')?.setAttribute('href',email?`mailto:${encodeURIComponent(email)}`:'');document.querySelector('#contactEmail strong')?.replaceChildren(email);document.getElementById('contactWhatsapp')?.setAttribute('href',safeHref(data.whatsappUrl));document.getElementById('phoneText').textContent=data.phone||'';document.getElementById('addressText').textContent=data.address||'';document.title=text(data,'contactTitle')||'';document.querySelector('meta[name="description"]')?.setAttribute('content',text(data,'contactDescription')||'')}
function setLanguage(next){language=next;localStorage.setItem('h1apps-language',language);document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';document.getElementById('arButton')?.classList.toggle('active',language==='ar');document.getElementById('enButton')?.classList.toggle('active',language==='en');if(window.contactData)render(window.contactData)}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('arButton')?.addEventListener('click',()=>{localStorage.setItem('h1apps-language','ar');location.reload()});document.getElementById('enButton')?.addEventListener('click',()=>{localStorage.setItem('h1apps-language','en');location.reload()});setLanguage(language)});
try{firebase.initializeApp(firebaseConfig);firebase.firestore().collection('site_contact').doc('contact').get().then(snapshot=>{window.contactData=snapshot.exists?snapshot.data():null;render(window.contactData)}).catch(()=>clearPage())}catch(error){clearPage()}
document.getElementById('contactForm')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,message=document.getElementById('formMessage'),submit=document.getElementById('submitButton');if(!form.checkValidity()){form.reportValidity();return}submit.disabled=true;message.className='';message.textContent=language==='ar'?'جاري إرسال الرسالة...':'Sending your message...';const data=Object.fromEntries(new FormData(form).entries());delete data.consent;data.status='new';data.submittedAt=firebase.firestore.FieldValue.serverTimestamp();data.language=language;try{const ref=await firebase.firestore().collection('contact_requests').add(data);form.reset();message.className='success';message.textContent=(language==='ar'?'تم إرسال رسالتك بنجاح. رقم الطلب: ':'Your message was sent successfully. Request ID: ')+ref.id}catch(error){message.className='error';message.textContent=language==='ar'?'تعذر إرسال الرسالة حاليًا. حاول مرة أخرى لاحقًا.':'We could not send your message right now. Please try again later.';console.error('Contact form submission failed',error)}finally{submit.disabled=false}});
