let language=localStorage.getItem('h1apps-language')||'en';
const firebaseConfig={apiKey:'AIzaSyDOlDg14fbH8kXfSbr6YCj6NECtEPJIdiU',authDomain:'h1words.firebaseapp.com',projectId:'h1words',storageBucket:'h1words.firebasestorage.app',messagingSenderId:'594662600507',appId:'1:594662600507:web:h1appswebsite'};
const fields=['contactKicker','contactTitle','contactDescription','formKicker','formTitle','formDescription','emailLabel','whatsappLabel','addressLabel','nameLabel','emailFieldLabel','phoneLabel','companyLabel','messageLabel','consentLabel','submitText','footerText','footerDeletion'];
const text=(data,key)=>language==='en'?data[`${key}En`]:data[key];
function clearPage(){document.body.classList.remove('data-pending');fields.forEach(key=>{const el=document.getElementById(key);if(el)el.textContent=''});['email','phoneText','addressText'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=''});document.getElementById('contactEmail')?.setAttribute('href','');document.getElementById('contactWhatsapp')?.setAttribute('href','');document.querySelector('.contact-shell')?.classList.add('site-data-empty')}
function render(data){if(!data||!Object.keys(data).length){clearPage();return}document.body.classList.remove('data-pending');document.querySelector('.contact-shell')?.classList.remove('site-data-empty');fields.forEach(key=>{const el=document.getElementById(key);if(el)el.textContent=text(data,key)||''});const email=data.email||'';document.getElementById('contactEmail')?.setAttribute('href',email?`mailto:${email}`:'');document.querySelector('#contactEmail strong')?.replaceChildren(email);document.getElementById('contactWhatsapp')?.setAttribute('href',data.whatsappUrl||'');document.getElementById('phoneText').textContent=data.phone||'';document.getElementById('addressText').textContent=data.address||'';document.title=text(data,'contactTitle')||'';document.querySelector('meta[name="description"]')?.setAttribute('content',text(data,'contactDescription')||'')}
function setLanguage(next){language=next;localStorage.setItem('h1apps-language',language);document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';document.getElementById('arButton')?.classList.toggle('active',language==='ar');document.getElementById('enButton')?.classList.toggle('active',language==='en');if(window.contactData)render(window.contactData)}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('arButton')?.addEventListener('click',()=>{localStorage.setItem('h1apps-language','ar');location.reload()});document.getElementById('enButton')?.addEventListener('click',()=>{localStorage.setItem('h1apps-language','en');location.reload()});setLanguage(language)});
try{firebase.initializeApp(firebaseConfig);firebase.firestore().collection('site_contact').doc('contact').get().then(snapshot=>{window.contactData=snapshot.exists?snapshot.data():null;render(window.contactData)}).catch(()=>clearPage())}catch(error){clearPage()}
document.getElementById('contactForm')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,message=document.getElementById('formMessage'),submit=document.getElementById('submitButton');if(!form.checkValidity()){form.reportValidity();return}submit.disabled=true;message.textContent='';const data=Object.fromEntries(new FormData(form).entries());delete data.consent;data.status='new';data.submittedAt=firebase.firestore.FieldValue.serverTimestamp();data.language=language;try{const ref=await firebase.firestore().collection('contact_requests').add(data);form.reset();message.className='success';message.textContent=ref.id}catch(error){message.className='error';message.textContent=''}finally{submit.disabled=false}});
