let language = localStorage.getItem('h1apps-language') || 'en';
const form = document.getElementById('projectForm');
const message = document.getElementById('formMessage');
const submit = document.getElementById('submitButton');
const firebaseConfig = {apiKey:'AIzaSyDOlDg14fbH8kXfSbr6YCj6NECtEPJIdiU',authDomain:'h1words.firebaseapp.com',projectId:'h1words',storageBucket:'h1words.firebasestorage.app',messagingSenderId:'594662600507',appId:'1:594662600507:web:h1appswebsite'};
function setLanguage(next){localStorage.setItem('h1apps-language',next);window.location.reload();}
function applyLanguage(){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';document.querySelectorAll('[data-ar]').forEach(el=>{if(language==='ar'){if(!el.dataset.en)el.dataset.en=el.textContent;el.textContent=el.dataset.ar}else if(el.dataset.en){el.textContent=el.dataset.en}});document.querySelectorAll('[data-placeholder-ar]').forEach(el=>{if(language==='ar'){if(!el.dataset.enPlaceholder)el.dataset.enPlaceholder=el.placeholder;el.placeholder=el.dataset.placeholderAr}else if(el.dataset.enPlaceholder)el.placeholder=el.dataset.enPlaceholder});document.getElementById('arButton').classList.toggle('active',language==='ar');document.getElementById('enButton').classList.toggle('active',language==='en');document.getElementById('year').textContent=new Date().getFullYear()}
document.getElementById('arButton').onclick=()=>setLanguage('ar');document.getElementById('enButton').onclick=()=>setLanguage('en');applyLanguage();
try{firebase.initializeApp(firebaseConfig)}catch(error){}
form.addEventListener('submit',async event=>{event.preventDefault();if(!form.checkValidity()){form.reportValidity();return}submit.disabled=true;message.className='';message.textContent=language==='ar'?'جاري إرسال الطلب...':'Sending your request...';const data=Object.fromEntries(new FormData(form).entries());delete data.consent;data.status='pending';data.submittedAt=firebase.firestore.FieldValue.serverTimestamp();data.updatedAt=firebase.firestore.FieldValue.serverTimestamp();data.language=language;try{const ref=await firebase.firestore().collection('project_requests').add(data);form.reset();message.className='success';message.textContent=(language==='ar'?'تم إرسال طلبك بنجاح. رقم الطلب: ':'Your request was sent successfully. Request ID: ')+ref.id}catch(error){message.className='error';message.textContent=language==='ar'?'تعذر إرسال الطلب، حاول مرة أخرى أو تواصل معنا مباشرة.':'We could not send the request. Please try again or contact us directly.';console.error(error)}finally{submit.disabled=false}});
if (!document.querySelector('script[data-premium-motion]')) { const s = document.createElement('script'); s.src = 'motion.js'; s.dataset.premiumMotion = 'true'; document.body.appendChild(s); }
