let currentLanguage = localStorage.getItem('h1apps-language') || 'en';
const safeHref=(value)=>{try{const url=new URL(String(value||''),window.location.href);return ['http:','https:','mailto:','tel:'].includes(url.protocol)?url.href:''}catch(_){return ''}};
const firebaseConfig = {apiKey:'AIzaSyDOlDg14fbH8kXfSbr6YCj6NECtEPJIdiU',authDomain:'h1words.firebaseapp.com',projectId:'h1words',storageBucket:'h1words.firebasestorage.app',messagingSenderId:'594662600507',appId:'1:594662600507:web:h1appswebsite'};
const ui = { ar:{navAbout:'من نحن',navProducts:'منتجاتنا',navContact:'تواصل معنا',startProject:'ابدأ مشروعك',productsKicker:'ما الذي نقدمه',aboutKicker:'عن H1APPS',discoverStory:'اكتشف قصتنا',learnMore:'اعرف أكثر',accountDeletion:'طلب حذف الحساب',direction:'rtl'}, en:{navAbout:'About us',navProducts:'Our work',navContact:'Contact',startProject:'Start your project',productsKicker:'What we do',aboutKicker:'About H1APPS',discoverStory:'Discover our story',learnMore:'Learn more',accountDeletion:'Delete account',direction:'ltr'} };
const managedFields = ['brandName','brandTagline','eyebrow','heroTitle','heroAccent','heroDescription','primaryCtaText','primaryCtaUrl','secondaryCtaText','secondaryCtaUrl','statOneValue','statOneLabel','statTwoValue','statTwoLabel','statThreeValue','statThreeLabel','featuresTitle','featuresDescription','featureOneTitle','featureOneDescription','featureTwoTitle','featureTwoDescription','featureThreeTitle','featureThreeDescription','aboutTitle','aboutDescription','footerText'];
function value(data,key){return currentLanguage==='en' ? data[`${key}En`] : data[key];}
function clearManaged(){document.body.classList.remove('data-pending');managedFields.forEach(key=>{const el=document.getElementById(key);if(el){el.textContent='';el.removeAttribute('href')}});document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=''});document.querySelector('main')?.classList.add('site-data-empty')}
function applyContent(data){if(!data||Object.keys(data).length===0){clearManaged();return}document.body.classList.remove('data-pending');document.querySelector('main')?.classList.remove('site-data-empty');managedFields.forEach(key=>{const el=document.getElementById(key);const text=value(data,key);if(el)el.textContent=text||''});const primary=document.getElementById('primaryCta');const secondary=document.getElementById('secondaryCta');if(primary){primary.textContent=value(data,'primaryCtaText')||'';primary.href=safeHref(data.primaryCtaUrl)}if(secondary){secondary.textContent=value(data,'secondaryCtaText')||'';secondary.href=safeHref(data.secondaryCtaUrl)}const emailLink=document.getElementById('emailLink');const whatsappLink=document.getElementById('whatsappLink');if(emailLink)emailLink.href=data.contactEmail?`mailto:${encodeURIComponent(data.contactEmail)}`:'';if(whatsappLink)whatsappLink.href=safeHref(data.whatsappUrl);const footerBrand=document.getElementById('footerBrand');if(footerBrand)footerBrand.textContent=data.brandName||'';const year=document.getElementById('year');if(year)year.textContent='';const title=value(data,'heroTitle');document.title=title||'';document.querySelector('meta[name="description"]')?.setAttribute('content',value(data,'heroDescription')||'');document.querySelector('meta[property="og:title"]')?.setAttribute('content',title||'');document.querySelector('meta[property="og:description"]')?.setAttribute('content',value(data,'heroDescription')||'')}
function setLanguage(language){currentLanguage=language;localStorage.setItem('h1apps-language',language);document.documentElement.lang=language;document.documentElement.dir=ui[language].direction;document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=ui[language][el.dataset.i18n]||''});document.getElementById('arButton')?.classList.toggle('active',language==='ar');document.getElementById('enButton')?.classList.toggle('active',language==='en');if(window.liveHomeData)applyContent(window.liveHomeData)}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('arButton')?.addEventListener('click',()=>{localStorage.setItem('h1apps-language','ar');location.reload()});document.getElementById('enButton')?.addEventListener('click',()=>{localStorage.setItem('h1apps-language','en');location.reload()});setLanguage(currentLanguage)});
try{firebase.initializeApp(firebaseConfig);firebase.firestore().doc('site_home/home').get().then(snapshot=>{window.liveHomeData=snapshot.exists?snapshot.data():null;applyContent(window.liveHomeData)}).catch(()=>clearManaged())}catch(error){clearManaged()}
